# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tiff Ting - Tasting the World
email: tiff.ting@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal account of my round-the-world trip spanning seven
  or more months between 2016 and 2017.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tiffting.com" # the base hostname & protocol for your site
twitter_username: tiffting
github_username:  tiffting

# Build settings
markdown: kramdown
