# This config file is meant for settings that affect your whole blog,
# values which you are expected to set up once and rarely need to
# edit after that. For technical reasons, this file is *NOT* reloaded
# automatically when you use 'jekyll serve'. If you change this file,
# please restart the server process.

# Site settings
title: Tiff tastes on the world
description: > # this means to ignore newlines until "baseurl:"
  An account of my 7+ month round-the-world trip.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.tiffting.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
